language: Java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_deploy:
  - ./gradlew releaseZip
deploy:
  provider: releases
  api_key:
    secure: e8RACm16/fFb0thjIN7/qUTAIhvTYrCbQ6LJiy2hv8Mn5rwkDnVPwTiGqBcvB/AuuQz+kLfg5KttyImW96ElIAQfDoHNdlEdOAyX986Qhd3aaiyW25LnYwws+m1pv5qgh8YaKPoNkWgegMNkY/+ZiwAXnxPwh51h+4tn/dGVy0jw+t8z70R4SKxJVuuoau8q45Vb5LMPFQ5hGPn7uVCrTQhMlzFr7idM5mUU32GR3qgm1sZs8xsM0Jz2RxGjBzld3KEcmU8X2x3+sJcHD4TQ7impuv1oubOwgkuQ5DBeXWpobSYeOF96ToRxTeib0X3J0hb5afHv+T1hOeWG82j365SoFLjfoeAaaQpabmstnPC19u9GprnHWqGZ595+awXRP4Ik3LofJ0Jrd+V4iHBkIoP2l9H1PzOFbh5hvqyPWhKncNfbRS8jNlZyx/wOAu+OLi2jdB1VmKRvmEPniyjmZIwHfQxPVCDab0cvdPxtNK+5JUzsqzRMMCpLX9spMK/mf+tqlA+mZmVYiw0wdiVNPZaZ+HIce9JxBjrxJtNpRCY87JKRGxubwdqgkxvQdNCkviomtMcfx3mz0aM2TXddLj2aJWWs0uMacyChZTD0O7qKhRptkEqn7faBqT8C2GOatkSTK/P3yZV8Vy8eKYtCRatLv3pM2OzKUrvCEOeHIAc=
  file_glob: true
  file: "./build/libs/JAlgoArena-Eureka-*.zip"
  skip_cleanup: true
  on:
    repo: skorzeniak/JAlgoArena-Eureka
    tags: true
